version: '3.8'

services:
	web:
		build: .
		command: python /drf_react_postgres_docker/manage.py runserver 0.0.0.0:8000
		volumes:
			- .:/drf_react_postgres_docker
		ports:
			- 8000:8000
		depends_on:
			- db
	db:
		image: postgres:11
		volumes:
			- postgres_data:/var/lib/postgresql/data/
		environment:
			- POSTGRES_NAME=postgres
			- POSTGRES_USER=postgres
			- POSTGRES_PASSWORD=postgres
			
volumes:
	postgres_data: