# Generated by Django 3.1.14 on 2022-03-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bookstore', '0002_auto_20220319_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='died',
            field=models.DateField(blank=True, null=True),
        ),
    ]
